

hypervisor-obj+= \
arch/arm/head.o \
arch/arm/traps.o \
arch/arm/timer.o \
arch/arm/gic.o \
arch/arm/vgic.o \
arch/arm/vtimer.o \
arch/arm/memory.o \
arch/arm/pageTable.o \
arch/arm/pio.o \
arch/arm/vtty.o
